/*
 * types.h
 *
 *  Created on: Mar 3, 2024
 *      Author: cotti
 */

#ifndef TYPES_H_
#define TYPES_H_

#include <omnetpp.h>

#include "phy_types.h"

typedef enum {
    MLME_ASSOCIATE_REQUEST,
    MLME_ASSOCIATE_INDICATION,
    MLME_ASSOCIATE_RESPONSE,
    MLME_ASSOCIATE_CONFIRM,

    MLME_DISASSOCIATE_REQUEST,
    MLME_DISASSOCIATE_INDICATION,
    MLME_DISASSOCIATE_CONFIRM,

    MLME_BEACON_NOTIFY_INDICATION,

    MLME_GET_REQUEST,
    MLME_GET_CONFIRM,

    MLME_GTS_REQUEST,
    MLME_GTS_INDICATION,
    MLME_GTS_CONFIRM,

    MLME_RESET_REQUEST,
    MLME_RESET_CONFIRM,

    MLME_RX_ENABLE_REQUEST,
    MLME_RX_ENABLE_CONFIRM,

    MLME_SCAN_REQUEST,
    MLME_SCAN_CONFIRM,

    MLME_COMM_STATUS_INDICATION,

    MLME_SET_REQUEST,
    MLME_SET_CONFIRM,

    MLME_START_REQUEST,
    MLME_START_CONFIRM,

    MLME_SYNC_REQUEST,

    MLME_SYNC_LOSS_INDICATION,

    MLME_POLL_REQUEST,
    MLME_POLL_CONFIRM,
} macMsgKind_t;

typedef enum {
    PD_DATA_REQUEST,
    PD_DATA_CONFIRM,
    PD_DATA_INDICATION,

    PLME_CCA_REQUEST,
    PLME_CCA_CONFIRM,

    PLME_GET_REQUEST,
    PLME_GET_CONFIRM,

    PLME_SET_REQUEST,
    PLME_SET_CONFIRM,

    PLME_SET_TRX_STATE_REQUEST,
    PLME_SET_TRX_STATE_CONFIRM,

    PLME_SWITCH_REQUEST,
    PLME_SWITCH_CONFIRM,
} phyMsgKind_t;













#endif /* TYPES_H_ */
